spring:
  application:
    name: jointProfile

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234567

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

server:
  port: 8081

connector:
  auth:
    url: localhost:8080/auth